version: "1.0"
services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: "mts_tariffs"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"